server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mydatabase}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    root: INFO
    com.nextech: DEBUG
  file:
    path: ./logs/application.log
  logback:
    rollingpolicy:
      max-history: 2
      total-size-cap: 100MB

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET:secret}

AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
AWS_S3_REGION: ${AWS_S3_REGION}
AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
AWS_SECRET_KEY: ${AWS_SECRET_KEY}
AWS_S3_BUCKET: ${AWS_S3_BUCKET}
CLOUDFLARE_BUCKET_SUBDOMAIN: ${CLOUDFLARE_BUCKET_SUBDOMAIN}